### PR TITLE
Task/sdk 265 create 1.3.1 release

### PR DESCRIPTION
**Pull request by Pramod-Redapple**
### What Does This PR Do?
updated readme file

### Checklist (if applicable):
[ ] item 1
[ ] item 2
[ ] item 3
[ ] item 4
[ ] item 5

### CODE REVIEW

**Review by drxeno02 — APPROVED** [review]
You can squash and merge.

**Comment by Pramod-Redapple** [comment]
i dont have access to merge it

**Comment by drxeno02** [comment]
> @drxeno02 i dont have access to merge it

@Pramod-Redapple You do. You can "Squash and merge". We require linear history.

Ref- https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits-in-github-desktop#about-squashing-a-commit

Ref- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-linear-history

**Comment by Pramod-Redapple** [comment]
> > @drxeno02 i dont have access to merge it
> 
> @Pramod-Redapple You do. You can "Squash and merge". We require linear history.
> 
> Ref- https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits-in-github-desktop#about-squashing-a-commit
> 
> Ref- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-linear-history

https://files.slack.com/files-pri/T8724C4R2-F05EZAYAB41/image.png

**Pull request merged**
